#!/usr/bin/env python

# A sample training component that trains a simple scikit-learn decision tree model.
# This implementation works in File mode and makes no assumptions about the input file names.
# Input is specified as CSV with a data point in each row and the labels in the first column.

from __future__ import print_function

import json
import os
import pickle
import sys
import traceback
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
import joblib
import argparse

import pandas as pd
from sklearn import tree

#  Read the content from s3 (mounted into the image by sagemaker)
prefix = '/opt/ml/'
input_data_path = os.path.join(prefix, 'input/data/train/diabetes.csv')
hyper_parameter_path  = os.path.join(prefix, 'input/config/hyperparameters.json')
model_output_path = os.path.join(prefix, 'model/')

# The function to execute the training.
def train():
    print('Starting the training.')

    try:
        # Load the training data from the s3 bucket
        data = pd.read_csv(input_data_path, sep='\t')
        print(data.shape)
        
        # # Load the diabetes dataset
        diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

        diabetes_X = data.drop(columns=['Y']).to_numpy()
        diabetes_y = data['Y'].to_numpy()

        # Use only one feature
        diabetes_X = diabetes_X[:, np.newaxis, 2]

        # Split the data into training/testing sets
        diabetes_X_train = diabetes_X[:-20]
        diabetes_X_test = diabetes_X[-20:]

        # Split the targets into training/testing sets
        diabetes_y_train = diabetes_y[:-20]
        diabetes_y_test = diabetes_y[-20:]

        # Create linear regression object
        regr = linear_model.LinearRegression()

        # Train the model using the training sets
        regr.fit(diabetes_X_train, diabetes_y_train)

        # Make predictions using the testing set
        diabetes_y_pred = regr.predict(diabetes_X_test)
        
        with open(os.path.join(model_output_path, 'model.joblib'), 'wb') as f:
            joblib.dump(regr, f)
    except Exception as e:
        print(e)
        # Write out an error file. This will be returned as the failureReason in the
        # DescribeTrainingJob result.
        # trc = traceback.format_exc()
        # with open(os.path.join(output_path, 'failure'), 'w') as s:
        #     s.write('Exception during training: ' + str(e) + '\n' + trc)
        # # Printing this causes the exception to be in the training job logs, as well.
        # print('Exception during training: ' + str(e) + '\n' + trc, file=sys.stderr)
        # # A non-zero exit code causes the training job to be marked as Failed.
        # sys.exit(255)


if __name__ == '__main__':
    train()

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)
